### ISSUE TITLE
RFE: optimize BTreeMap::findSmaller, findSmallerNode for primitive keys

### ISSUE THREAD

**Issue by jandam** [jankotek/mapdb#438]
BTreeMap::findSmallerNode, findSmallerNode are not optimized for primitive keys and uses linear search instead of binary search.

Please consider this RFE for 2.0.

**Comment by cubefriendly** [comment]
Hi,
Quick question so I understand this issue. I thought that this method uses the comparator given to perform a binary search. Primitive keys bypass the comparator?

Also, is it a problem found in MapDB 1.0.6 as well or is it only because you have implemented new primitive types (the array).

Keep up the good work I am looking forward to play with what you have done

**Comment by jankotek** [comment]
In 2.0 binary search is performed in primitive forms by BTreeKeySerializer in most cases. But I think `findSmallerNode` uses linear scan for some reason.

**Comment by esnellman** [comment]
Here blog post with evidence showing how performant binary search can be in C++, might be relevant to Java.

"Binary Search *eliminates* Branch Mispredictions"
http://www.pvk.ca/Blog/2012/07/03/binary-search-star-eliminates-star-branch-mispredictions/

**Comment by jankotek** [comment]
This was rewritten in 3.0
