### ISSUE TITLE
Prevent collection serialization by some tools

### ISSUE THREAD

**Issue by jankotek** [jankotek/mapdb#444]
This is thrown if user tries to serialize HTreeMap by some jackson thingy:
```
java.lang.ClassCastException: org.mapdb.BTreeMap$DirNode cannot be cast to org.mapdb.HTreeMap$ExpireLinkNode
        org.mapdb.HTreeMap.expireLinkBump(HTreeMap.java:1378)
        org.mapdb.HTreeMap$HashIterator.findNextLinkedNode(HTreeMap.java:1053)
        org.mapdb.HTreeMap$HashIterator.<init>(HTreeMap.java:970)
        org.mapdb.HTreeMap$EntryIterator.<init>(HTreeMap.java:1132)
        org.mapdb.HTreeMap$5.iterator(HTreeMap.java:916)
        org.codehaus.jackson.map.ser.std.MapSerializer.serializeFields(MapSerializer.java:232)
        org.codehaus.jackson.map.ser.std.MapSerializer.serialize(MapSerializer.java:186)
        org.codehaus.jackson.map.ser.std.MapSerializer.serialize(MapSerializer.java:23)
        org.codehaus.jackson.map.ser.StdSerializerProvider._serializeValue(StdSerializerProvider.java:659)
        org.codehaus.jackson.map.ser.StdSerializerProvider.serializeValue(StdSerializerProvider.java:271)
        org.codehaus.jackson.map.ObjectWriter.writeValue(ObjectWriter.java:325)
        org.codehaus.jackson.jaxrs.JacksonJsonProvider.writeTo(JacksonJsonProvider.java:556)
        com.sun.jersey.json.impl.provider.entity.JacksonProviderProxy.writeTo(JacksonProviderProxy.java:160)
        com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:302)
        com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1510)
        com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
        com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
        com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
        com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:540)
        com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:715)
        javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

```

**Comment by michelemauro** [comment]
This one is probably quite difficoult to solve: every tool has its own annotation or configuration to mark a class as not serializable. There are two possible paths, IMHO:

- document the classes as "not meant for serialization" by such tools.
- find someone to build compatibility subprojects that provide the necessary serializers/machinery/gluecode to do these kind of serializations.

Why would someone dump a potentially VERY large map in JSON escapes me, however.

**Comment by cubefriendly** [comment]
I think the main issue in this case is that the message is not clear. I had similar issues with Guava and it is fair to say that you should not serialize the collections from MapDB.

A good solution here would be to find a way to make the message clearer. 

I think what happened here is what happens a lot when an object is so well integrated into your application you forget what you are working with.

When you have simply a Map<String,String> properties you tend to forget that your backend is a complex off heap in memory implementation and you think HashMap naturally. 

A simple solution would be to put the error message in the FAQ and when someone googles it, it will end up reading an entry telling him he tries to serialize something he shouldn't.

**Comment by rlcomstock3** [comment]
>> Why would someone dump a potentially VERY large map in JSON escapes me, however.

Because I am the one who was attempting to do this I think I might be able to shed some light on why one would attempt to do this.

My specific use case was a REST website.  My data seemed to fit with the MapDB model very well.  It was so easy to use that I decided to give it a try.  My site had some other design requirements and one of them was to allow authentication to view their own data.  I used a token that was generated with a successful login and then passed with every request.  I decided that the expire after last read would be a perfect solution.  But after I wrote the code the tokens in the table didn't seem to be going away after an hour of not using them.  So I tried to display all of the active ones.  Because at most in testing I would have 20 or 30 entry in this file.  This is when I found the error.  And when I make this call it seems to break the entire MapDB session, this error is not recoverable unless I restarted tomcat.

It might also be important to note that almost all the other "Maps" I was using in MapDB were being dumped the exact same way as this one.  I would select other maps and just pass them to the Jackson Serialized to turn them into JSON.  In all other cases it seemed to work flawlessly, it only seems to break in this one case when the Map supported expired entries.

I have come to understand though this discussion that maybe MapDB isn't the best fit for what I am trying to do.  I can appreciate that and will look for a little bit better solution for my specific use case.  I think that MapDB is a fantastic product and I will continue to keep tabs on it as it grows and improves.  And when another problem is presented I hope to be able to use it again.

Thanks for your help in tracking down the problem.

**Comment by cubefriendly** [comment]
I think you'll have no other choice but to resolve this issue for each library.

in Jackson, you can register specific serializer for a type. It can be interesting to create a small project like mapdb-jackson where you can have all the util classes for integrating mapdb in Jackson. I don't think it should be part of the core.

**Comment by jankotek** [comment]
MapDB collections now implement `Serializable` interface and are serializable, but they will turn into their Java Util counterparts (`HTreeMap` becomes `ConcurrentHashMap` after deserialization).  

I have no time to implement more 'bulletproof' solution.  There are too many 3th party libraries and too many combinations.
