### ISSUE TITLE
Variables stored twice?

### ISSUE THREAD

**Issue by datumbox** [jankotek/MapDB#471]
Hello, 

I am planning to use MapDB as the default storage engine of [Datumbox Machine Learning Framework](https://github.com/datumbox/datumbox-framework/) and I have a question concerning how the objects are serialized.

The Machine Learning models are stored in objects that contain several small variables (such as the size of the dataset, number of features etc) and a few huge Maps (the weights of the models). We want to use MapDB to avoid having those huge Maps in memory and also persist all the objects that are generated from training.

The problem is that the huge Maps are wrapped inside the objects that we wish to persist. This is shown on the dummy test case below. The question is, if we store the models as shown below, will we end up saving the Maps twice? Also when we read again the persisted objects, do we load the entrire Map in memory?

Thanks in advance!
Vasilis

```java
public class Example {
    public static void main(String[] args) {
        DB db = DBMaker.newFileDB(new File("testdb")).closeOnJvmShutdown().make();
        Test t = new Test(10, db);
        //Populate the huge map
        for(int i=0;i<100;++i) {
            t.addInMap(i,i);
        }
        
        //QUESTION 1: When I put the object in map db, do I end up storing the huge map twice?
        db.getAtomicVar("obj").set(t);
        
        //close/remove everything
        db.close();
        db = null;
        t = null;
        
        db = DBMaker.newFileDB(new File("testdb")).closeOnJvmShutdown().make();
        
        //QUESTION 2: When I read the t object, do I also read the entire y Map?
        t = (Test) db.getAtomicVar("obj").get();
        db.close();
    }
}

class Test implements Serializable {
    // here goes several small variables
    private int x = 0;
    
    // here goes few huge maps which we want to avoid having in memory
    private Map<Integer, Integer> y;
    
    public Test(int x, DB db) {
        this.x = x;
        this.y = db.getHashMap("SOME_HUGE_MAP");
    }
    
    public void addInMap(Integer k, Integer v) {
        y.put(k, v);
    }
}
```

**Comment by rmraya** [comment]
If you know in advance that the inner map is huge, save it in its own file and store a link to the corresponding map in your main class. 

Regards,
Rodolfo

-- 
Rodolfo M. Raya
Sent with Airmail

On March 22, 2015 at 10:20:42 PM, Datumbox (notifications@github.com) wrote:

Hello,

I am planning to use MapDB as the default storage engine of Datumbox Machine Learning Framework and I have a question concerning how the objects are serialized.

The Machine Learning models are stored in objects that contain several small variables (such as the size of the dataset, number of features etc) and a few huge Maps (the weights of the models). We want to use MapDB to avoid having those huge Maps in memory and also persist all the objects that are generated from training.

The problem is that the huge Maps are wrapped inside the objects that we wish to persist. This is shown on the dummy test case below. The question is, if we store the models as shown below, will we end up saving the Maps twice? Also when we read again the persisted objects, do we load the entrire Map in memory?

Thanks in advance!
Vasilis

public class Example {
    public static void main(String[] args) {
        DB db = DBMaker.newFileDB(new File("testdb")).closeOnJvmShutdown().make();
        Test t = new Test(10, db);
        //Populate the huge map
        for(int i=0;i<100;++i) {
            t.addInMap(i,i);
        }

        //QUESTION 1: When I put the object in map db, do I end up storing the huge map twice?
        db.getAtomicVar("obj").set(t);

        //close/remove everything
        db.close();
        db = null;
        t = null;

        db = DBMaker.newFileDB(new File("testdb")).closeOnJvmShutdown().make();

        //QUESTION 2: When I read the t object, do I also read the entire y Map?
        t = (Test) db.getAtomicVar("obj").get();
        db.close();
    }
}

class Test implements Serializable {
    // here goes several small variables
    private int x = 0;

    // here goes few huge maps which we want to avoid having in memory
    private Map<Integer, Integer> y;

    public Test(int x, DB db) {
        this.x = x;
        this.y = db.getHashMap("SOME_HUGE_MAP");
    }

    public void addInMap(Integer k, Integer v) {
        y.put(k, v);
    }
}

**Comment by datumbox** [comment]
Thanks for the reply rmraya.

We would like to avoid storing it separately because it would mess up the architecture of the framework. The other storage engines that we use (Serialized files and MongoDB) are able to store everything in the same "database". Based on limited tests that I run with MapDB it seems that it is quite clever and does the work properly:

1. It does not store twice the map. We can see this if we store separately the map and compare the size of the file with the one of the Object Test. They have the same size.
2. It does not seem to load immediately the entire internal map when loading the atomic variable.

If one of the contributors who know the mechanics of the library could validate this, it would be great. 

Thanks a lot!
Vasilis

**Comment by jankotek** [comment]
Hi,

named objects in mapdb such as maps should be stored only once (mapdb serialization will only store name reference.

Also it does not load entire maps

**Comment by datumbox** [comment]
Hi jankotek,

Thanks for the confirmation. :)

BTW MapDB is now fully integrated with Datumbox. We should release the new version within a couple of weeks.
