### ISSUE TITLE
SEVERE: java.lang.AssertionError: unknown trans log instruction '0' at log offset: 16

### ISSUE THREAD

**Issue by cszamudio** [jankotek/mapdb#509]
I started seeing this AssertionError on MapDB version 1.0.7. 
```
May 07, 2015 11:47:01 AM org.mapdb.StoreWAL replayLogFile
SEVERE: java.lang.AssertionError: unknown trans log instruction '0' at log offset: 16
```
I noticed that this issue was resolved in 1.0.5, but I think it might still be an issue.

I am using a very simple map created as:
```
db = DBMaker.newFileDB(dbFile)
				.make();
```
The map has over 2 million simple entries <Integer, Date>
with no concurrent access to the map.  The error occurs on the db.commit() statement.
```
May 07, 2015 11:47:01 AM org.mapdb.StoreWAL replayLogFile
SEVERE: java.lang.AssertionError: unknown trans log instruction '0' at log offset: 16
     at org.mapdb.StoreWAL.replayLogFile(StoreWAL.java:827)
     at org.mapdb.StoreWAL.commit(StoreWAL.java:606)
     at org.mapdb.EngineWrapper.commit(EngineWrapper.java:94)
     at org.mapdb.DB.commit(DB.java:1605)
```
It's intermittent.  The MapDb file is still readable and I can subsequently add and remove to it even after the error is thrown by closing and then re-opening.

**Comment by jankotek** [comment]
It is happening at  offset 16, where no data are yet added. My guess is that there is empty commit or file was not synced yet. Will look into this.

**Comment by zepernick** [comment]
I have been struggling with this issue intermittently as well.  I have multiple threads working off the cache which I think might be part of the problem, but I am not sure.  It usually goes away if I synchronize the method that is accessing the cache, but this really hinders my performance.  I have tried putting synchronize blocks inside the method instead, but I have not been able to get that right because it still pops up every now and then.

**Comment by jankotek** [comment]
Can not replicate, please use 2.0 branch.
