### ISSUE TITLE
cant delete problem mapdb files after DBmaker.fileDB()....make() throws

### ISSUE THREAD

**Issue by Groostav** [jankotek/mapdb#521]
Hey guys,

I've got some code that attempts to connect to an existing database. It works if we have no version conflicts.

When we do have version (or other) problems: I want to kickoff a process (prompting the user, backing up files, deleting the problem files, etc) to correct the issue. The problem is that if in the same callstack (read: without any delay as below) I do a 

```Java
try{
     DBMaker
         .fileDB(dbFile)
         //...
         .make()
}
catch(IOException | IOError e){
    //on our flow, we do some UI stuff here, but that's not necessary for this bug
    Files.delete(dbFile);
}
```

then `Files.delete` throws 'this file is already in use by another process'. 

This is probably [JRE 4715154](http://bugs.java.com/bugdatabase/view_bug.do?bug_id=4715154)'s fault, but I just thought you should know.

If you throw in the klooge suggested [here](http://stackoverflow.com/questions/991489/i-cant-delete-a-file-in-java):
 ```Java
try{
     DBMaker
         .fileDB(dbFile)
         //...
         .make()
}
catch(IOException | IOError e){
    //add a stupid gc & sleep call to let any streams drop out of scope (?)
    { System.gc(); Thread.sleep(200); }

    Files.delete(dbFile);
}
```

Still no good.

Any suggestions?

**Comment by jankotek** [comment]
Hi,

MapDB has GC hack which forces mmap files to unmap before it is closed, in theory it should not be affected by this problem. There is also a `DBMaker.deleteFilesAfterClose()` and `DBMaker.closeOnJVMShutdown()` which could in theory solve this problem. 

Also calling ``db.close()`` or something line ``db.getEngine().[index or data]volume.close()`` could solve a problem.

Otherwise I dont have good answer. Disable mmap files or do not use windows. 

Closing this issue, It is on my TODO list and I believe there are already open issues which cover it.
