### ISSUE TITLE
Could DB make or get ?

### ISSUE THREAD

**Issue by bwzhang2011** [jankotek/mapdb#549]
@jankotek, as we use dbMaker to create db associated with either memory one or file based one.
as for the file one, the current use cases need us to create the mapdb (just mean the DB instance) many times. just like the application will generate daily file and I will create the mapdb instance based on the daily file. so here comes my doubt, if I could not set the db instance to be the global one, I should get the DB (or open such exists) due to whether the file exists or not. so I dare Maker class should leave us such to open the exists file for DB creation. what's more, I notice that HTreeMapMaker  to  create the HTreeMap with makeOrGet(). so how could I generate the HTreeMap based on different file. here comes some use cases:
```
public class AbstractMonitorCompositeStoreImpl extends MapStoreAdapter<String, MonitorComposite>
		implements IMonitorCompositeStore {
	@Override
	public void store(final String key, final MonitorComposite value) {

	}

	@Override
	public MonitorComposite load(final String key) {
		return null;
	}

	@Override
	public Set<String> loadAllKeys() {
		return null;
	}

}
```
just like the mapstore (from hazelcast) I want to persist the object MonitorComposite  into mapdb with special key. and I want to generate many files based the key with some configuration just like
parentpath/date/db.data    the date change daily and each time when it invoke store I will load the DB according to the key (just for HTreeMap creation) and then store value afterwards.

**Comment by dmk23** [comment]
+1, I was about to report essentially the same issue.

In our example we are running two services, let's call them Producer and Consumer in the same JVM. Producer collects some application activity and records it into MapDB. Consumer provides a web interface to view the results. Both access the same DB persisted to the same file.

In our first test case we had both services initialize DB with the identical calls to ```.make()``` and obtain a map with the same ```.makeOrGet```. Then we found that updates written by Producer are not visible to Consumer, however if a JVM is restarted they both get the same view of what the DB was at the time of shutdown, but any new updates from Producer are still not visible to Consumer.

For now we've fixed this problem by creating a centrally shared DB object, but it seems quite dangerous that MapDB is not able to handle this issue by itself. We could imagine situations when the same file is accessed by different JVM processes or shared over network, etc. In those cases it is important to be absolutely assured when all the updates get flushed to the file by a Producer and how a Consumer can get assurances of accessing the latest data from the persisted store populated by Producer.

We also have an immediate use case when after writing to DB we need to send it to archive. Right now I am not sure what is the proper way to ensure all the writes are completed and the file is in its final state. Is ```db.close()``` necessary (perhaps because it would tell OS to be done with the file?), or there is a more lightweight API to achieve full persistence / prepare file for moving?

**Comment by jankotek** [comment]
I am not sure i understand. You want to open single file multiple times within single instance? I mean there are multiple DB instances over single file?

This is not really supported, MapDB crashes / looses data when used this way. And MapDB should refuse to open already opened file. However file-locking is tricky to do right. And I have not implemented it yet.

I would recommend some sort of static global field. You could also use IOC framework.

**Comment by dmk23** [comment]
Yes, at the moment we have implemented a global static field (actually a synchronized map, keyed by the file path key). There are a few remaining questions / suggestions though:

1. MapDB docs should state clearly that opening the same file via multiple DB objects is not supported and could lead to data corruption if both are writing
2. If an attempt to open the same file is made MapDB should at least throw an error or warning if that is not supported or could lead to data corruption (or alternatively safely return same DB).
3. Regardless of sharing, I'd like to know the proper way to fully flush DB writes (for a mmap'd file) in preparation for copying the file, without shutting down the JVM.

Last question is the most critical, I do not see this explained clearly on the page on Durability -
http://www.mapdb.org/doc/durability-versus-speed.html

**Comment by jankotek** [comment]
> 1) MapDB docs should state clearly 

Documentation will follow soon

>  2) open the same file is made MapDB should at least throw an error or warning 

I just added exclusive file locking to master branch, beta-3 should block multiple DB instances over single file. See #305. 

`FileChannel.lock()` is not best, so I am going to add second optional locking method based on Lock file with heartbeat. It works very well for H2 database.

> 3) Regardless of sharing, I'd like to know the proper way to fully flush DB writes (for a mmap'd file) in preparation for copying the file, without shutting down the JVM.

Closing DB should be enough. Also `DB.commit()` should work if there are no writes until copying finishes. When transactions are disabled the `DB.commit()` will sync write cache to disk, so files should be consistent until next write.

I will keep this issue open until documentation is updated.

**Comment by dmk23** [comment]
Thank you!

If a DB is closed (for file copying) could it be re-opened or we'd have to re-create a DB object anew? If the second approach is necessary - the file lock should be released when DB is closed.

When you say ```DB.commit()``` should work, does it mean it works if there are no writes AFTER it is called (the condition that I suppose we'd have to ensure by synchronizing of our DB write/commit ops)? Would all in-process writes be fully flushed and persisted when ```.commit()``` returns? If that is the case should there be any performance advantage (or risk) to using ```.commit()``` over ```.close()```

Finally, I'd like to see if there are any special situations with mmap'd files - since OS is heavily involved in managing them. Would a system call to copy a file succeed regardless of whether OS (Linux) has flushed some pages from memory to disk? Would it cause them to be flushed?

I am also considering use of snapshots to generate compacted files that can be shared. It would involve something like doing ```.snapshot()``` and than using returned DB to populate a pump that would produce a compressed new DB that we can close and share. The questions here are 1) what is the performance overhead of enabling snapshots over a write-heavy DB? 2) What is the proper / fastest way/API to implement this copying via pump, does passing the original BTree collection (per https://github.com/jankotek/mapdb/issues/545) ensure the fastest / best compaction?

**Comment by jankotek** [comment]
> DB.commit() should work, does it mean it works if there are no writes AFTER it is called 
Yes

> (the condition that I suppose we'd have to ensure by synchronizing of our DB write/commit ops)?
Yes

> Would all in-process writes be fully flushed and persisted when .commit() returns?
Yes. I call `MappedByteBuffer.force()` on all opened buffers. Javadoc says it is synced on local filesystems (no guarantees over network). 

If transaction are enabled, commit is more complex, since WAL exists, but guarantees are same (all data synced to disk).

> Finally, I'd like to see if there are any special situations with mmap'd files - since OS is heavily involved in managing them. Would a system call to copy a file succeed regardless of whether OS (Linux) has flushed some pages from memory to disk? Would it cause them to be flushed?

I am not really sure I can answer this question. Perhaps copy is not dependent on flush, since it can take pages from write cache, before they are fully synced. And details depends on tool used to copy data, I do not believe there is atomic `copyFile` kernel call. 

> I am also considering use of snapshots to generate compacted files that can be shared. It would involve something like doing .snapshot() 

I have no benchmarks for snapshots yet. This whole things needs to be documented, bench-marked and various settings needs to be exposed (there are perhaps 5 snapshot modes). 

I think what you want are incremental backups. They should be added in about 3 weeks. 

> 2) What is the proper / fastest way/API to implement this copying via pump, does passing the original BTree collection (per #545) ensure the fastest / best compaction?

Yes and no. This method will iterate over collection in reverse order, which is not fastest possible way. BTreeMap leaf nodes are linked in natural order, so regular Iterator is much faster. So the fastest way is to use regular Iterator as Pump Source, but that will produce BTreeMap in reverse order. 

Perhaps best way is not to use data pump, but dump key-value pairs into binary file. I could provide utility method for that.

**Comment by dmk23** [comment]
I suppose ```MappedByteBuffer.force()``` should be sufficient and take care of all issues between JVM and OS/mmap. Otherwise JVM would have to be considered buggy...

Yes, I want incremental backups, BUT with full compression / optimization of BTrees. Is this functionality intended to replace or enhance snapshots? They both sound very similar...

Could you provide full sample code for using Pump Source in the way you just described (for fastest compressed BTree backups in natural order). Pumps are perhaps the least documented part of the code and it is hard to figure out from the examples the implications of choosing one option over another...

Just to be clear I think we'd want that data export to be in the proper order so it could be opened and read just like any other file. I'm also thinking that while the source file could have smaller nodes optimized for heavy write workload (e.g. ```.nodeSize(16)```) our archives probably should have larger node sizes to optimize for compression / reads / scans (e.g. ```.nodeSize(128)```). Whatever export method is preferred, we'd want to be able to implement such format changes as part of "incremental backups"

Also what would happen if we create a pump using a BTree that might be currently updated (no snapshots)? Are we only at risk of missing some of the records or outright data corruption is possible?

**Comment by dmk23** [comment]
One more thing now that we've brought up ```MappedByteBuffer```

I just did a quick search through the source and do not see any calls to ```MappedByteBuffer.load()``` anywhere. While it makes perfect sense to leave paging decisions to OS in most cases, I believe it would also be helpful to expose this call via an API to end user for cases when it is important to warm up specific collections for random access. The alternative is a full scan with unnecessary unpacking of data.

**Comment by jankotek** [comment]
>  do not see any calls to MappedByteBuffer.load()

There are some parts which could benefit, I will see what I can do about that.

**Comment by dmk23** [comment]
I think you could add a ```load()``` API to DB which in turn would pass it to MappedByteBuffer

Any feedback on my last set of questions?

**Comment by bwzhang2011** [comment]
@jankotek, any update with such issue ?

**Comment by jankotek** [comment]
I just added load method and updated documentation a bit:

`Store.forDB(db).fileLoad()`

**Comment by bwzhang2011** [comment]
@jankotek, thanks for review and look forward to the document.
