### ISSUE TITLE
Is there a read-only mode for mapdb? DB.hashMap method is synchronzied, and is there a nonblocking method?

### ISSUE THREAD

**Issue by sxpujs** [jankotek/mapdb#574]
Hi Jankotek:

We use mapdb.2.0-beta4. Is there a read-only mode for mapdb? In our project, we build and store the metric bitmaps in mapdb every day. Once the mapdb file is created, it won't change any more because they are offline data. We read the mapdb file like below:

    public volatile LoadingCache<String, DB> dbCache = CacheBuilder.newBuilder()
        .build(new CacheLoader<String, DB>() {
      @Override
      public DB load(String key) throws Exception {
        File fileEntry = new File(key);
        DB dbDisk = DBMaker
            .fileDB(fileEntry)
            .fileMmapEnable()
            .fileMmapCleanerHackEnable()
            .cacheHashTableEnable()
            .cacheSize(100000)
            .transactionDisable()
            .make();
        return dbDisk;
      }
    });

Another question is DB.hashMap is synchronized, it will cause bad performance because we load and read the map frequently. Below is from your DB.class

    synchronized public <K,V> HTreeMap<K,V> hashMap(String name){
        return hashMap(name, null, null, null);
    }

I'm looking forward to your answer, thanks in advance.

**Comment by jankotek** [comment]
DBMaker.readOnlyEnable() option will use readonly mode. 

I have no plan to remove `synchronized` any time soon. It manipulates named 
catalog and that should be thread-safe operation. Perhaps create some cache for 
hashmaps outside DB object. 

Eventually `synchronized` will be replaced with ReadWriteLock or something bit 
more concurrent, but it has very low priority, could take a months or years. 
If it is important for you, I could implement  it sooner, but that would cost money.

Jan


On Thursday, September 03, 2015 06:24:42 孙修鹏 wrote:


Hi Jankotek: 
We use mapdb.2.0-beta4. Is there a read-only mode for mapdb? In our project, we 
build and store the metric bitmaps in mapdb every day. Once the mapdb file is 
created, it won't change any more because they are offline data. We read the 
mapdb file like below: 
public volatile LoadingCache<String, DB> dbCache = CacheBuilder.newBuilder()
    .build(new CacheLoader<String, DB>() {
  @Override
  public DB load(String key) throws Exception {
    File fileEntry = new File(key);
    DB dbDisk = DBMaker
        .fileDB(fileEntry)
        .fileMmapEnable()
        .fileMmapCleanerHackEnable()
        .cacheHashTableEnable()
        .cacheSize(100000)
        .transactionDisable()
        .make();
    return dbDisk;
  }
});
 
Another question is DB.hashMap is synchronized, it will cause bad performance 
because we load and read the map frequently. Below is from your DB.class 
synchronized public <K,V> HTreeMap<K,V> hashMap(String name){
    return hashMap(name, null, null, null);
}
 
I'm looking forward to your answer, thanks in advance. 
—Reply to this email directly or view it on GitHub[1].[2]




--------
[1] https://github.com/jankotek/mapdb/issues/574
[2] 
https://github.com/notifications/beacon/AAV6bWGZKrzj7oPN2nGnGGsfPUju5J52ks
5ouEGagaJpZM4F3PST.gif

**Comment by sxpujs** [comment]
Thanks for your reply, I will use local cache to improve the performance.
