### ISSUE TITLE
Eliminate guava

### ISSUE THREAD

**Issue by cy6erGn0m** [jankotek/mapdb#686]
Guava has too unstable API so this is why libraries should never ever depend on it as it may cause user's great pain

**Comment by jankotek** [comment]
Guava saves me a lot of work, also MapDB will implement some Guava interfaces (MultiMap, Bimap).  

Do you have some links which outline their unstable API?

**Comment by lmprice** [comment]
I know that their @Beta API's are subject to change, but in my experience, Guava is very stable in their API.

**Comment by danieljue** [comment]
Guava can be quite a time saver and in the past seemed to adopt useful utils faster than their apache counterparts (not to mention the implementations are pretty high performance).  One responsibility of using it should be to state explicitly what range of Guava versions are supported by your application.  The POM usually takes care of this by setting a version.

**Comment by cy6erGn0m** [comment]
No, it doesn't. Once you use guava you force user to user the same major version. So user could be unable to use another library that depends on another major version so it will be impossible to find the best common version that works well with both 3rd parties. The only alternative is to support very wide range of guava versions

**Comment by datumbox** [comment]
Jan, correct me if i am wrong but in version 1 of mapdb the library was "advertised" as zero dependency embedded db. Version 3 brings quite many dependences and as some ppl pointed out this could cause problems. what are your thoughts on the number of dependences that mapdb will have on the next versions?

**Comment by jankotek** [comment]
MapDB3 also requires Java8+ and Unsafe. Plus its written in Kotlin (IDE dep). 

MapDB was zero dependency library for past ten years since JDBM1. It was increasingly difficult to maintain it this way. About 30% of code was waste. Also in MapDB 2 the code become  more complex (for example parallel compaction) and I could not write that in plain Java 6.

There is also commercial reason. Most companies I do consulting for, are using Java8 and deps are no problem. 

Here is takeaway:

 - Guava is going to stay. MapDB will become increasingly more tied to it. MapDB will also implement collections such as `Bimap` and `MultiMap` so Guava will become part of public API.

 - Various dependency issues can be solved with text preprocessing. Some flavour of MapDB could be compiled against Guava with renamed package (it already works with `mapdb-renamed` package).  

- Size can be reduced with proguard (removes unused classes). Works pretty well for Scala. Will provide instructions.

- See above, there will be fat-mapdb, which will contain all dependencies, but compressed in alternative package names. It should have around 2MB? 

- I think right now MapDB has about 14 MB of deps. Eclipse Collections, Guava, LZ4J, byte code frameworks... I want to keep deps under 20MB.

- I will contribute some changes to Guava and EC, so MapDB might depend on newest version of those :-(

**Comment by vizh** [comment]
Thank you! When we can wait for fat-mapdb reduced with proguard?
