### ISSUE TITLE
Specifying classloader 

### ISSUE THREAD

**Issue by besherman** [jankotek/mapdb#740]
In issue #555 it is detailed how to specify a classloader when using OSGI. But the methods discussed are no longer there. Has this functionality been removed?

**Comment by msx80** [comment]
Indeed, this is an important functionality, it looks like it was not implemented in 3.x.x.
I hope it will be reimplemented.

**Comment by msx80** [comment]
I've found a workaround: i noticed that when DB is created it uses the classloader stored into Thread.contextClassLoader, so setting it before opening the DB can force your classloader:
`Thread.currentThread().setContextClassLoader(childClassLoader);`

I don't know if it's the expected behavior or even good practice, but it works. The contextClassLoader can be reset after opening the db

**Comment by jankotek** [comment]
This issue was already targeting it in 2.0, but it was not ported to 3.0 https://github.com/jankotek/mapdb/issues/555

**Comment by nddipiazza** [comment]
Hey @jankotek i noticed that https://github.com/jankotek/mapdb/commit/3d1ddbf186607d1a5022b699de57dcf5275a3dd0 references a classloader setting so that I can tell a `DB` to use a particular classloader. But it is not in the latest mapdb version.

I tried the `Thread.currentThread().setContextClassLoader(childClassLoader);` work around but couldn't seem to get that to work either. 

how can I use a custom classloader?
