### ISSUE TITLE
How to Store ConcurrentMap<String, List<String>>

### ISSUE THREAD

**Issue by ondev** [jankotek/mapdb#791]
```
DB db = DBMaker.fileDB(tmpFile).make();
ConcurrentMap<String, List<Object>> map = db.hashMap("tmp", Serializer.STRING, Serializer.xxx)
```

what's the xxx in version 3.0.1?

**Comment by jankotek** [comment]
XXX is serializer used for values. You can use db.getDefaulterializer()

**Comment by hoakzie** [comment]
ConcurrentMap<String, List<Object>> map = db.hashMap("tmp", 
    Serializer.STRING, indexDB.getDefaultSerializer());

Gives the compile error:

incompatible types: no instance(s) of type variable(s) K,V exist so that org.mapdb.DB.HashMapMaker<K,V> conforms to java.util.concurrent.ConcurrentMap<java.lang.String,java.util.List<java.lang.Object>>

Is this done differently in 3.0.5?

**Comment by rameshmandri** [comment]
@jankotek jankotek  @hoakzie hoakzie  

I am also having same problem 

Type safety: The expression of type HTreeMap needs unchecked
conversion to conform to ConcurrentMap>.
Type safety: The expression of type GroupSerializer needs unchecked
conversion to conform to Serializer.
Type safety: Unchecked invocation hashMap(String, GroupSerializer, GroupSerializer) of the generic method hashMap(String, Serializer, Serializer) of type DB.
