### ISSUE TITLE
BTreeMap Custom Comparator 

### ISSUE THREAD

**Issue by zeus82** [jankotek/mapdb#853]
The BTreeMap doesn't appear to support a custom Comparator like the TreeMap does.  The TreeMap has a constructor that takes in a Comparator.  Is there another way to support this behavior with the BTreeMap?

**Comment by jankotek** [comment]
BTreeMap allows custom comparator. 

`db.treeMap("name").comparator(comparator).make()...`

**Comment by djspiewak** [comment]
For the benefit of anyone else who finds this issue via Google…

Jan's snippet above does not compile on any release of MapDB 3.0. You'll note if you crack open the source code that `TreeMaker` actually hard-codes `_keySerializer` for the `comparator` parameter of `BTreeMap`. Custom comparators are only supported indirectly via key serialization, but even that is somewhat difficult to leverage directly since serializer serialization is stubbed out (meaning that you must either manage serializer instances manually, or restrict yourself to only the built-in serializers).
